### ISSUE TITLE
I got the Top1 ACC in Val is 0.7102. Hope to get some help.

### ISSUE THREAD

**Issue by zanonShao** [eric8607242/SGNAS#1]
Thanks for your great work.
I tried to reproduce your experiment on CIFA-100.

- Firstly, I setted `warmup_epochs=50 search_epochs=0` in _cifar_config.yml_, to train the supernet.
- Secondly,I setted  `warmup_epochs=0 search_epochs=50`, to train the generator.
- Finally, I ran `'python3 train_cifar.py --cfg cifar_config.yml --flops 100'` to generate the model and retrain it.

However, I got the Top1 ACC in Val is 0.7102.
So please tell me what I did wrong.

The curve of training Supernet
![train_Supernet](https://user-images.githubusercontent.com/19763498/112718768-0c26be80-8f30-11eb-8db1-1983fedfa1fe.jpg)
The curve of searching
![search](https://user-images.githubusercontent.com/19763498/112718787-29f42380-8f30-11eb-934f-84e2f543db2e.jpg)
The curve of training retraining
![retrain](https://user-images.githubusercontent.com/19763498/112718795-38dad600-8f30-11eb-924c-73cea87d3ba1.jpg)

**Comment by eric8607242** [comment]
Hello,
We run our all experiments on ImageNet, instead of cifar100.
Can you give more illustration about this issue ?
